name: Build and Release (Manual Style)

on:
  push:
    tags:
      - 'v*'  # Runs when you push a tag like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Change this to your version

      - name: 🧪 Build with Maven
        run: mvn clean package

      - name: 📦 Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: 📤 Upload JAR asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/Neon-Copper-*.jar  # Replace with your actual JAR path
          asset_name: copper.jar           # Rename if desired
          asset_content_type: application/java-archive

      - name: 📚 Publish changelog (optional)
        uses: StuYarrow/publish-release@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body_path: ./CHANGELOG.md  # Optional: Path to a changelog file
